wscript: add workaround for XCode 9.1.0
We have a CI machine with XCode 9.1.0 on Mac OS 10.13.  XCode 9.1.0
seems to have a bug which cause a valid C initializer "{0}" as missing
field:

    ../src/interfaces/csp_if_udp.c:61:37: error: missing field
    'sin_family' initializer [-Werror,-Wmissing-field-initializers]
            struct sockaddr_in server_addr = {0};
                                               ^
    1 error generated.

The compiler from XCode 9.1.0 is

    $ gcc --version
    Apple LLVM version 9.1.0 (clang-902.0.39.2)
    Target: x86_64-apple-darwin17.7.0

So make sure to add -Wno-missing-field-initializers for XCode 9.1.0.
-Wmissing-field-initializers is enabled by -Wextra.

All newer XCode seems to be OK.

Signed-off-by: Yasushi SHOJI <yashi@spacecubics.com>